# Generated by Django 5.1.7 on 2025-04-13 10:49

import tracker.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_transaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=tracker.models.EncryptedDecimalField(decimal_places=2, max_digits=10),
        ),
    ]
